// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgEDlPvoKCNiZluw-ydqb5c4ug24jsr3w',
    appId: '1:485399308801:web:b7381778d025e8ae56ee00',
    messagingSenderId: '485399308801',
    projectId: 'care-flow-bc527',
    authDomain: 'care-flow-bc527.firebaseapp.com',
    storageBucket: 'care-flow-bc527.firebasestorage.app',
    measurementId: 'G-5P2MRWD4J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJzV3T2NdXZPg_BD32kWjs8j6I9liVDw',
    appId: '1:485399308801:android:2354d754e3ae8e0c56ee00',
    messagingSenderId: '485399308801',
    projectId: 'care-flow-bc527',
    storageBucket: 'care-flow-bc527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxyC9ij0Jg_bT_NamVpF8goYpGBwsdVo',
    appId: '1:485399308801:ios:dad2262ee3923f2956ee00',
    messagingSenderId: '485399308801',
    projectId: 'care-flow-bc527',
    storageBucket: 'care-flow-bc527.firebasestorage.app',
    iosBundleId: 'com.example.careFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxyC9ij0Jg_bT_NamVpF8goYpGBwsdVo',
    appId: '1:485399308801:ios:dad2262ee3923f2956ee00',
    messagingSenderId: '485399308801',
    projectId: 'care-flow-bc527',
    storageBucket: 'care-flow-bc527.firebasestorage.app',
    iosBundleId: 'com.example.careFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgEDlPvoKCNiZluw-ydqb5c4ug24jsr3w',
    appId: '1:485399308801:web:e0af69c0f0b5010856ee00',
    messagingSenderId: '485399308801',
    projectId: 'care-flow-bc527',
    authDomain: 'care-flow-bc527.firebaseapp.com',
    storageBucket: 'care-flow-bc527.firebasestorage.app',
    measurementId: 'G-XSS3Y5KLED',
  );
}
